# Generated by Django 6.1.1 on 2026-09-19 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '__first__'),
        ('commercial', '0001_initial'),
        ('configurateur', '__first__'),
        ('reseau', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('acompte_montant', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('financement_type', models.CharField(choices=[('comptant', 'Comptant'), ('credit', 'Crédit'), ('loa', 'LOA')], default='comptant', max_length=15)),
                ('etape', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('financement_en_cours', 'Financement en cours'), ('en_production', 'En production'), ('en_transit', 'Fret maritime en transit'), ('dedouanement', 'Dédouanement Douala'), ('prete_livraison', 'Prête à la livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='nouvelle', max_length=25)),
                ('date_prevue_livraison', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='reseau.concession')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='configurateur.configuration')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='commercial.lead')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('canal', models.CharField(choices=[('momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('virement', 'Virement bancaire'), ('carte', 'Carte bancaire'), ('especes', 'Espèces (en concession)')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=15)),
                ('reference_externe', models.CharField(blank=True, help_text='Identifiant de transaction renvoyé par MoMo / Orange Money / la banque.', max_length=100)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiculePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('disponible', 'Disponible'), ('reserve', 'Réservé'), ('vendu', 'Vendu'), ('archive', 'Archivé')], default='en_preparation', max_length=20)),
                ('date_arrivee', models.DateField(blank=True, null=True)),
                ('kilometrage', models.PositiveIntegerField(default=0, help_text='Utile pour les véhicules de démonstration.')),
                ('concession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='reseau.concession')),
                ('finition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unites', to='catalogue.finition')),
                ('habitacle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites', to='catalogue.habitacle')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unites', to='catalogue.vehiculemodele')),
                ('teinte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites', to='catalogue.teinte')),
            ],
            options={
                'verbose_name': 'Véhicule physique',
                'verbose_name_plural': 'Véhicules physiques (stock VIN)',
                'ordering': ['-date_arrivee'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='vehicule_physique',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande', to='ventes.vehiculephysique'),
        ),
    ]
