# Generated by Django 6.1.1 on 2026-09-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('prix_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('mensualite_estimee', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('enregistree', 'Enregistrée'), ('convertie', 'Convertie en commande')], default='brouillon', max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to=settings.AUTH_USER_MODEL)),
                ('finition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='catalogue.finition')),
                ('habitacle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='catalogue.habitacle')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='catalogue.vehiculemodele')),
                ('options', models.ManyToManyField(blank=True, related_name='configurations', to='catalogue.optionpack')),
                ('teinte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='catalogue.teinte')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
