# Generated by Django 6.1.1 on 2026-09-19 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reseau', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom_contact', models.CharField(blank=True, max_length=150)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('telephone_contact', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('site_web', 'Site web'), ('telephone', 'Téléphone'), ('whatsapp', 'WhatsApp'), ('showroom', 'Showroom'), ('salon', 'Salon / événement')], default='site_web', max_length=20)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('qualifie', 'Qualifié'), ('essai_planifie', 'Essai planifié'), ('devis_envoye', 'Devis envoyé'), ('gagne', 'Gagné'), ('perdu', 'Perdu')], default='nouveau', max_length=20)),
                ('energie_interet', models.CharField(blank=True, max_length=25)),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('premier_contact_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Essai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_heure', models.DateTimeField()),
                ('duree_minutes', models.PositiveSmallIntegerField(default=45)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('realise', 'Réalisé'), ('annule', 'Annulé'), ('absence', 'Absence client')], default='planifie', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='essais', to='reseau.concession')),
                ('conseiller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essais_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Essai',
                'verbose_name_plural': 'Essais',
                'ordering': ['date_heure'],
            },
        ),
    ]
