# Generated by Django 6.1.1 on 2026-09-19 18:54

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculeModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('carrosserie', models.CharField(choices=[('berline', 'Berline'), ('suv', 'SUV'), ('citadine', 'Citadine'), ('break', 'Break'), ('pickup', 'Pick-up'), ('monospace', 'Monospace')], max_length=20)),
                ('energie', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('hybride_rechargeable', 'Hybride rechargeable'), ('electrique', 'Électrique')], max_length=25)),
                ('prix_base', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('autonomie_km', models.PositiveIntegerField(blank=True, null=True)),
                ('capacite_batterie_kwh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temps_recharge_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('consommation_l_100km', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('puissance_ch', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de véhicule',
                'verbose_name_plural': 'Modèles de véhicules',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='OptionPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=12)),
                ('categorie', models.CharField(choices=[('confort', 'Confort'), ('securite', 'Sécurité'), ('multimedia', 'Multimédia et navigation'), ('style', 'Style et jantes')], max_length=20)),
                ('energies_compatibles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('hybride_rechargeable', 'Hybride rechargeable'), ('electrique', 'Électrique')], max_length=25), blank=True, default=list, help_text='Vide = compatible avec toutes les énergies.')),
                ('disponible', models.BooleanField(default=True)),
                ('modeles_compatibles', models.ManyToManyField(blank=True, related_name='options', to='catalogue.vehiculemodele')),
            ],
            options={
                'verbose_name': 'Option / Pack',
                'verbose_name_plural': 'Options / Packs',
            },
        ),
        migrations.CreateModel(
            name='Motorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(help_text='Ex : 4 cylindres 2.0 essence + 2 moteurs électriques', max_length=100)),
                ('cylindree_cm3', models.PositiveIntegerField(blank=True, null=True)),
                ('boite', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], max_length=20)),
                ('couple_nm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tension_batterie_v', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temps_0_100_s', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorisations', to='catalogue.vehiculemodele')),
            ],
            options={
                'verbose_name': 'Motorisation',
                'verbose_name_plural': 'Motorisations',
            },
        ),
        migrations.CreateModel(
            name='MediaVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], default='photo', max_length=10)),
                ('vue', models.CharField(choices=[('exterieur', 'Extérieur'), ('interieur', 'Intérieur')], default='exterieur', max_length=10)),
                ('fichier', models.FileField(upload_to='medias/%Y/%m/')),
                ('legende', models.CharField(blank=True, max_length=150)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='catalogue.vehiculemodele')),
            ],
            options={
                'verbose_name': 'Média véhicule',
                'verbose_name_plural': 'Médias véhicule',
                'ordering': ['modele', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('manuel_utilisateur', 'Manuel utilisateur'), ('fiche_technique', 'Fiche technique'), ('garantie', 'Conditions de garantie')], max_length=25)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=2)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalogue.vehiculemodele')),
            ],
            options={
                'verbose_name': 'Document véhicule',
                'verbose_name_plural': 'Documents véhicule',
            },
        ),
        migrations.CreateModel(
            name='Teinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('code_hex', models.CharField(help_text='Ex : #1C1C1C', max_length=7)),
                ('supplement_prix', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teintes', to='catalogue.vehiculemodele')),
            ],
            options={
                'verbose_name': 'Teinte',
                'verbose_name_plural': 'Teintes',
                'unique_together': {('modele', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Habitacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('supplement_prix', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitacles', to='catalogue.vehiculemodele')),
            ],
            options={
                'verbose_name': 'Habitacle',
                'verbose_name_plural': 'Habitacles',
                'unique_together': {('modele', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Finition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('supplement_prix', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('puissance_ch', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('autonomie_km', models.PositiveIntegerField(blank=True, null=True)),
                ('equipements_inclus', models.TextField(blank=True, help_text='Liste des équipements, un par ligne.')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finitions', to='catalogue.vehiculemodele')),
            ],
            options={
                'verbose_name': 'Finition',
                'verbose_name_plural': 'Finitions',
                'ordering': ['modele', 'ordre'],
                'unique_together': {('modele', 'nom')},
            },
        ),
    ]
