# Generated by Django 6.1.1 on 2026-09-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('capacite_essai_quotidienne', models.PositiveSmallIntegerField(default=4, help_text="Nombre d'essais routiers pouvant être planifiés par jour.")),
                ('horaires', models.CharField(blank=True, help_text='Ex : Lun-Ven 8h-18h, Sam 9h-13h', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concession',
                'verbose_name_plural': 'Concessions',
                'ordering': ['ville', 'nom'],
            },
        ),
    ]
